### ISSUE TITLE
Exception: Problem with flags: ['run_summarization.py', '--enhanced_attnetion=True']

### ISSUE THREAD

**Issue by Git-oNmE** [JD-AI-Research-NLP/SGG#2]
I was running with the command `python run_summarization.py --mode=True --coverage=False --enhanced_attnetion=True --data_path=dataset/testset_* --batch_size=64 --vocab_path=dataset/vocab --log_root=SG --exp_name=myexperiment --single_pass=True`, and I got the error message like below.
I tried to change the "--enhanced_attnetion" option to False, but didn't work. Error message was similar.
Anyone knows how to solve it? Thanks!
```
Traceback (most recent call last):
  File "run_summarization.py", line 324, in <module>
    tf.app.run()
  File "/home/hlf/anaconda3/envs/SGG_tf1_py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_summarization.py", line 270, in main
    raise Exception("Problem with flags: %s" % unused_argv)
Exception: Problem with flags: ['run_summarization.py', '--enhanced_attnetion=True']
```

**Comment by pierre-zhao** [comment]
Hi,

Sorry for this late reply. I have fixed the typos in README (attnetion -> attention).
